title: bilalsul' blog
email: bilalworku@proton.me
baseurl: "/blog"
url: "https://bilalsul.github.io"
github_username: bilalsul

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html

header_pages:
  - about.md
